[lldb] Fix -Wctad-maybe-unsupported in Alarm.cpp (NFC)
llvm-project/lldb/source/Host/common/Alarm.cpp:37:5:
error: 'lock_guard' may not intend to support class template argument deduction [-Werror,-Wctad-maybe-unsupported]
    std::lock_guard alarm_guard(m_alarm_mutex);
    ^

(cherry picked from commit ba97dc8c7a8fc26516fbdfe822343bc4d38fe3db)