Fix test failure
rdar://127869147
(Clang.CAS.driver-cache-launcher.c failing on internal/clang/1600)

/Users/local/jenkins/workspace/stage1-RA_internal_clang_1600_13/llvm-project/clang/test/CAS/driver-cache-launcher.c:77:23: error: DISABLE-MCCAS-NOT: excluded string found in input
// DISABLE-MCCAS-NOT: "-mllvm"

(cherry picked from commit ae3196fff1d5a5cf545500681e16e4b9efc607fc)