[lldb-mcp] Fix building for Windows
This fixes build errors like these:

    lldb/tools/lldb-mcp/lldb-mcp.cpp:45:41: error: use of undeclared identifier '_O_BINARY'
       45 |   int result = _setmode(fileno(stdout), _O_BINARY);
          |                                         ^
    lldb/tools/lldb-mcp/lldb-mcp.cpp:47:36: error: use of undeclared identifier '_O_BINARY'
       47 |   result = _setmode(fileno(stdin), _O_BINARY);
          |                                    ^

(cherry picked from commit 1ec06886a4a0dac110e93aef027697734b8013ab)