[lldb] Allow "var" expr variables to be modified (#5651)
Unconditionally call `SwiftExpressionVariable::SetIsModifiable`, for both `let` and `var` variables. Previously `SetIsModifiable(false)` was called for `let` variables - now `var` variables will result in `SetIsModifiable(true)`.

This fixes the following bug:

    (lldb) expr var $count = 123
    (lldb) expr $count = 456
    error: expression failed to parse:
    error: <EXPR>:3:1: error: cannot assign to value: '$count' is immutable
    $count = 456
    ^~

rdar://102675900