[lldb] Fix a warning
This patch fixes:

  lldb/source/Plugins/Platform/Windows/PlatformWindows.cpp:386:13:
  error: comparison between NULL and non-pointer ('lldb::addr_t' (aka
  'unsigned long') and NULL) [-Werror,-Wnull-arithmetic]

(cherry picked from commit ee4b462693b1ffeccfe1b8fcf0a0c12896ac6e6a)