[lldb] Fix build error in ValueObject test
Fixes 0cbc4983adcdbbd85ccb38b2dfbfe5985367b1b2.

llvm-project/lldb/unittests/ValueObject/DynamicValueObjectLocalBuffer.cpp(221): error C2065: 'u_int8_t': undeclared identifier

(cherry picked from commit 9d83790d170cc0a06179514e2ab739f7ecafb78c)