[lldb] Improve error message when inline tests fail to launch (#220621)
Currently these tests fail much later with the following error when the
process fails to launch:

```
AssertionError: False is not true : inline test did not hit a single breakpoint
```

(cherry picked from commit 309c55493d86ba6caf2851f0df4102cf21cabe2c)