Fix bug with -fcas-emit-casid-file during replay.
When using MCCAS replay with the option -fcas-emit-casid-file, we would
see the error:

fatal error: caching backend error: cached output file has unknown path
<path-to-file>/file.casid

This patch fixes that issue by just having a raw_fd_ostream in the
CompilerInstance that points to the .casid file rather than having it
be one of the outputs of the CompilerInstance.

This patch also makes sure that the .casid file is written even if there
is a ResultCallback in the MachOCASWriter.

(cherry picked from commit 2cd3dc3dfb6e09c4ab9f9120383fcb96c5a061fc)