[lldb] Fix a warning
This patch fixes:

  lldb/source/Plugins/SystemRuntime/MacOSX/AbortWithPayloadFrameRecognizer.cpp:177:10:
  error: unused variable 'str_len' [-Werror,-Wunused-variable]

(cherry picked from commit 1fcddc0dfa1b371bc0b278438d5f47cf8d03b511)