Wrap constructor in #ifndef NDEBUG
After 51650649d9b62bfd025fdf674368584bddf4841a,
TestSwiftASTContext fails when -NDEBUG is set because the
constructor is wrapped in #ifndef NDEBUG. This change wraps the
use of the constructor as well.

Resolves the failure:

/home/michellecasbon/release_0.12/llvm-project/lldb/unittests/Symbol/TestSwiftASTContext.cpp:64:29: error:
      no matching constructor for initialization of
      'lldb_private::SwiftASTContext'
  SwiftASTContextTester() : SwiftASTContext() {}
                            ^