[lldb] Use validation combination of options in TestAbbreviations (#125270)
Name and line number are part of different option groups and are not
compatible.

```
(lldb) breakpoint set -n foo -l 10
error: invalid combination of options for the given command
```

The help output for `breakpoint set` confirms this. This patch updates
the test to use two compatible options. With the improved error
reporting from #125125 this becomes an issue.

(cherry picked from commit dbabad0fc04e7106a07dbeeb8ff23dc32ce6b2c6)