[DirectX] Add missing argument to addPassesToEmitFile.
Without it, build with -Werror fails:

llvm/lib/Target/DirectX/DirectXTargetMachine.h:36:65: error: non-virtual member function marked 'override' hides virtual member function
   36 |                            MachineModuleInfoWrapperPass *MMIWP) override;
      |